name: Infection

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  LIBRDKAFKA_VERSION: v1.8.0

jobs:
  Infection:
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install librdkafka
        run: |
          chmod +x .ci/install_rdkafka.sh
          .ci/install_rdkafka.sh

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
          coverage: "pcov"
          extensions: "rdkafka"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: Run Infection
        run: vendor/bin/infection --threads=$(nproc)
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
