name: "Static Analysis"

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  LIBRDKAFKA_VERSION: v1.8.0

jobs:
  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Install librdkafka
        run: |
          chmod +x .ci/install_rdkafka.sh
          .ci/install_rdkafka.sh

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
          coverage: "none"
          extensions: "rdkafka"
          tools: "cs2pr, pecl"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: "Run a static analysis with phpstan/phpstan"
        run: "vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"
